java -jar beagle-1.1.3.jar -follow -repository $1/ambrose -dest beagleOutput/ambrose
java -jar beagle-1.1.3.jar -follow -repository $1/closure-compiler -dest beagleOutput/closure-compiler
java -jar beagle-1.1.3.jar -follow -repository $1/closure-templates -dest beagleOutput/closure-templates
java -jar beagle-1.1.3.jar -follow -repository $1/compile-testing -dest beagleOutput/compile-testing
java -jar beagle-1.1.3.jar -follow -repository $1/docx4j -dest beagleOutput/docx4j
java -jar beagle-1.1.3.jar -follow -repository $1/error-prone -dest beagleOutput/error-prone
java -jar beagle-1.1.3.jar -follow -repository $1/Fenzo -dest beagleOutput/Fenzo
java -jar beagle-1.1.3.jar -follow -repository $1/Git-Credential-Manager-for-Mac-and-Linux -dest beagleOutput/Git-Credential-Manager-for-Mac-and-Linux
java -jar beagle-1.1.3.jar -follow -repository $1/google-java-format -dest beagleOutput/google-java-format
java -jar beagle-1.1.3.jar -follow -repository $1/governator -dest beagleOutput/governator
java -jar beagle-1.1.3.jar -follow -repository $1/GraphJet -dest beagleOutput/GraphJet
java -jar beagle-1.1.3.jar -follow -repository $1/greenmail -dest beagleOutput/greenmail
java -jar beagle-1.1.3.jar -follow -repository $1/gson -dest beagleOutput/gson
java -jar beagle-1.1.3.jar -follow -repository $1/guice -dest beagleOutput/guice
java -jar beagle-1.1.3.jar -follow -repository $1/hbc -dest beagleOutput/hbc
java -jar beagle-1.1.3.jar -follow -repository $1/hibernate-ogm -dest beagleOutput/hibernate-ogm
java -jar beagle-1.1.3.jar -follow -repository $1/hibernate-search -dest beagleOutput/hibernate-search
java -jar beagle-1.1.3.jar -follow -repository $1/hollow -dest beagleOutput/hollow
java -jar beagle-1.1.3.jar -follow -repository $1/hraven -dest beagleOutput/hraven
java -jar beagle-1.1.3.jar -follow -repository $1/incubator-datasketches-java -dest beagleOutput/incubator-datasketches-java
java -jar beagle-1.1.3.jar -follow -repository $1/initializr -dest beagleOutput/initializr
java -jar beagle-1.1.3.jar -follow -repository $1/ion-java -dest beagleOutput/ion-java
java -jar beagle-1.1.3.jar -follow -repository $1/javaanpr -dest beagleOutput/javaanpr
java -jar beagle-1.1.3.jar -follow -repository $1/javaparser -dest beagleOutput/javaparser
java -jar beagle-1.1.3.jar -follow -repository $1/jbehave-core -dest beagleOutput/jbehave-core
java -jar beagle-1.1.3.jar -follow -repository $1/jbot -dest beagleOutput/jbot
java -jar beagle-1.1.3.jar -follow -repository $1/jimfs -dest beagleOutput/jimfs
java -jar beagle-1.1.3.jar -follow -repository $1/lavagna -dest beagleOutput/lavagna
java -jar beagle-1.1.3.jar -follow -repository $1/mantis -dest beagleOutput/mantis
java -jar beagle-1.1.3.jar -follow -repository $1/nanohttpd -dest beagleOutput/nanohttpd
java -jar beagle-1.1.3.jar -follow -repository $1/nodes -dest beagleOutput/nodes
java -jar beagle-1.1.3.jar -follow -repository $1/objenesis -dest beagleOutput/objenesis
java -jar beagle-1.1.3.jar -follow -repository $1/open-location-code -dest beagleOutput/open-location-code
java -jar beagle-1.1.3.jar -follow -repository $1/optaplanner -dest beagleOutput/optaplanner
java -jar beagle-1.1.3.jar -follow -repository $1/protostuff -dest beagleOutput/protostuff
java -jar beagle-1.1.3.jar -follow -repository $1/shopizer -dest beagleOutput/shopizer
java -jar beagle-1.1.3.jar -follow -repository $1/spring-cloud-azure -dest beagleOutput/spring-cloud-azure
java -jar beagle-1.1.3.jar -follow -repository $1/spring-data-cosmosdb -dest beagleOutput/spring-data-cosmosdb
java -jar beagle-1.1.3.jar -follow -repository $1/spring-data-gremlin -dest beagleOutput/spring-data-gremlin
java -jar beagle-1.1.3.jar -follow -repository $1/swagger-core -dest beagleOutput/swagger-core
java -jar beagle-1.1.3.jar -follow -repository $1/truth -dest beagleOutput/truth
java -jar beagle-1.1.3.jar -follow -repository $1/zuul -dest beagleOutput/zuul