git clone https://github.com/google/guice
git clone https://github.com/google/gson
git clone https://github.com/google/closure-compiler
git clone https://github.com/google/open-location-code
git clone https://github.com/google/google-java-format
git clone https://github.com/google/error-prone
git clone https://github.com/google/truth
git clone https://github.com/google/jimfs
git clone https://github.com/google/compile-testing
git clone https://github.com/google/closure-templates
git clone https://github.com/amzn/ion-java
git clone https://github.com/twitter/nodes
git clone https://github.com/twitter/hraven
git clone https://github.com/twitter/ambrose
git clone https://github.com/twitter/GraphJet
git clone https://github.com/twitter/hbc
git clone https://github.com/apache/incubator-datasketches-java
git clone https://github.com/microsoft/spring-cloud-azure
git clone https://github.com/microsoft/spring-data-cosmosdb
git clone https://github.com/microsoft/spring-data-gremlin
git clone https://github.com/microsoft/Git-Credential-Manager-for-Mac-and-Linux
git clone https://github.com/spring-io/initializr
git clone https://github.com/javaparser/javaparser
git clone https://github.com/plutext/docx4j
git clone https://github.com/jbehave/jbehave-core
git clone https://github.com/hibernate/hibernate-ogm
git clone https://github.com/shopizer-ecommerce/shopizer
git clone https://github.com/kiegroup/optaplanner
git clone https://github.com/swagger-api/swagger-core
git clone https://github.com/rampatra/jbot
git clone https://github.com/NanoHttpd/nanohttpd
git clone https://github.com/digitalfondue/lavagna
git clone https://github.com/protostuff/protostuff
git clone https://github.com/hibernate/hibernate-search
git clone https://github.com/easymock/objenesis
git clone https://github.com/oskopek/javaanpr
git clone https://github.com/greenmail-mail-test/greenmail
git clone https://github.com/Netflix/zuul
git clone https://github.com/Netflix/mantis
git clone https://github.com/Netflix/hollow
git clone https://github.com/Netflix/governator
git clone https://github.com/Netflix/Fenzo
